name: swui package

on: push

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com
      - name: Configure committer
        run: |
          git config user.name "GitHub Actions Bot2"
          git config user.email "<titi@dfgfdg.fr>"
      - run: yarn
      - run: yarn release
      - run: yarn build
